"""
Unified Planner — Single-call plan-then-execute planner
=========================================================
Replaces the 3-call pipeline (intent_parser → task_decomposer → per-step
action_selector) with ONE LLM call that produces a structured action plan.

Output: A list of concrete browser actions with checkpoints, ready for
deterministic batch execution — no LLM needed between actions.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Optional

from ..config import AgentConfig, default_config
from ..llm_client import LLMClient
from ..model_router import ModelTier, route_for_planning
from ..models import ActionObject

logger = logging.getLogger(__name__)


class PlannedStep:
    """A single step in the execution plan."""
    __slots__ = ("action", "target", "value", "checkpoint", "description")

    def __init__(
        self, action: str, target: str = "", value: str = "",
        checkpoint: bool = False, description: str = "",
    ):
        self.action = action
        self.target = target
        self.value = value
        self.checkpoint = checkpoint
        self.description = description

    def to_action_object(self) -> ActionObject:
        """Convert to ActionObject for the browser executor."""
        selector = self.target if self.target else None
        val = self.value if self.value else None
        return ActionObject(
            action=self.action,
            selector=selector,
            value=val,
            timeout_ms=5000,
        )

    def to_dict(self) -> dict:
        return {
            "action": self.action,
            "target": self.target,
            "value": self.value,
            "checkpoint": self.checkpoint,
            "description": self.description,
        }


class ExecutionPlan:
    """Complete execution plan generated by one LLM call."""

    def __init__(
        self,
        task_type: str,
        steps: list[PlannedStep],
        success_criteria: str = "",
        domain: str = "",
    ):
        self.task_type = task_type
        self.steps = steps
        self.success_criteria = success_criteria
        self.domain = domain

    @property
    def checkpoint_indices(self) -> list[int]:
        """Return indices of steps that are checkpoints."""
        return [i for i, s in enumerate(self.steps) if s.checkpoint]


# ── Compact planning prompt (token-efficient) ────────────────────────────────

_PLAN_PROMPT = """You are a browser automation planner. Given a user task, output a JSON action plan.

RULES:
- Output ONLY valid JSON, no explanation
- Each step is a browser action: navigate, fill, click, scroll, extract, wait
- "target" = element description (text label, role, or placeholder: e.g. "search_input", "search_button", "cheapest_product")
- "value" = URL for navigate, text for fill, extraction spec for extract (e.g. "cheapest", "products"), null otherwise
- Mark important verification points as "checkpoint": true
- For search tasks on e-commerce / sites:
  1. navigate to store / site URL
  2. fill search box with query (automatically submits search)
  3. scroll or wait (brief pause for results to settle)
  4. extract items / prices / direct links (with checkpoint: true)
  5. click first_product or cheapest_product if the user asks to open/view the product
- Keep plans concise: 3-6 steps maximum
- The last step should be a checkpoint

USER TASK: {task}

Output JSON:
{{
  "task_type": "<product_search|price_comparison|navigation|data_extraction|other>",
  "domain": "<topic>",
  "success_criteria": "<what success looks like>",
  "steps": [
    {{"action": "navigate", "target": "", "value": "<url>", "checkpoint": false, "description": "Go to website"}},
    {{"action": "fill", "target": "search_input", "value": "<search text>", "checkpoint": false, "description": "Search for query"}},
    {{"action": "extract", "target": "cheapest_product", "value": "cheapest", "checkpoint": true, "description": "Extract product details and direct link"}}
  ]
}}"""


class UnifiedPlanner:
    """
    Single-call planner that generates a complete browser action plan.

    Replaces IntentParser (M1) + TaskDecomposer (M2) for the optimized path.
    Uses model routing to pick fast vs reasoning model.
    """

    def __init__(self, config: AgentConfig = default_config):
        self.config = config
        self.llm = LLMClient(config)

    async def plan(self, task: str, retry_count: int = 0) -> tuple[ExecutionPlan, int]:
        """
        Generate a complete execution plan from a natural-language task.

        Args:
            task: User's natural-language task description.
            retry_count: Number of planning retries (triggers reasoning model).

        Returns:
            Tuple of (ExecutionPlan, tokens_used).
        """
        tier = route_for_planning(task_type="", retry_count=retry_count)
        prompt = _PLAN_PROMPT.format(task=task)

        logger.info(f"[Planner] Planning task: '{task[:80]}' (tier={tier.value})")

        if tier == ModelTier.REASONING:
            response, tokens = await self.llm.complete_reasoning(prompt)
        else:
            response, tokens = await self.llm.complete_fast(prompt)

        plan = self._parse_plan(response, task)
        logger.info(
            f"[Planner] Plan generated: {plan.task_type} | "
            f"{len(plan.steps)} steps | {len(plan.checkpoint_indices)} checkpoints | "
            f"{tokens} tokens"
        )
        return plan, tokens

    async def replan(
        self, task: str, error: str, completed_steps: list[str],
        current_url: str = "", current_title: str = "",
    ) -> tuple[ExecutionPlan, int]:
        """
        Generate a recovery plan after execution failure.
        Always uses the reasoning model.
        """
        prompt = f"""You are a browser automation recovery planner.

The original task FAILED. Generate a NEW plan to recover.

ORIGINAL TASK: {task}
ERROR: {error}
COMPLETED STEPS: {json.dumps(completed_steps)}
CURRENT PAGE: {current_url} - "{current_title}"

Output ONLY valid JSON with the same schema as before.
Focus on alternative approaches. Do NOT repeat failed actions."""

        response, tokens = await self.llm.complete_reasoning(prompt)
        plan = self._parse_plan(response, task)
        logger.info(f"[Planner] Recovery plan: {len(plan.steps)} steps | {tokens} tokens")
        return plan, tokens

    def _parse_plan(self, response: str, fallback_task: str) -> ExecutionPlan:
        """Parse LLM response into an ExecutionPlan."""
        json_match = re.search(r"\{[\s\S]*\}", response)
        if not json_match:
            logger.warning("[Planner] No JSON found, using fallback plan.")
            return self._fallback_plan(fallback_task)

        try:
            data = json.loads(json_match.group())
            steps = []
            for s in data.get("steps", []):
                steps.append(PlannedStep(
                    action=s.get("action", "wait"),
                    target=s.get("target", ""),
                    value=s.get("value", ""),
                    checkpoint=s.get("checkpoint", False),
                    description=s.get("description", ""),
                ))

            if not steps:
                return self._fallback_plan(fallback_task)

            # Ensure last step is a checkpoint
            steps[-1].checkpoint = True

            return ExecutionPlan(
                task_type=data.get("task_type", "other"),
                steps=steps,
                success_criteria=data.get("success_criteria", ""),
                domain=data.get("domain", ""),
            )
        except (json.JSONDecodeError, TypeError, ValueError, KeyError) as e:
            logger.warning(f"[Planner] Parse error: {e}. Using fallback.")
            return self._fallback_plan(fallback_task)

    @staticmethod
    def _fallback_plan(task: str) -> ExecutionPlan:
        """Minimal fallback plan when parsing fails."""
        return ExecutionPlan(
            task_type="other",
            domain="general",
            success_criteria="Complete the user's task",
            steps=[
                PlannedStep(
                    action="navigate",
                    value="https://www.google.com",
                    description="Go to Google",
                ),
                PlannedStep(
                    action="fill",
                    target="search input",
                    value=task[:100],
                    description="Search for the task",
                ),
                PlannedStep(
                    action="click",
                    target="search button",
                    checkpoint=True,
                    description="Submit search",
                ),
                PlannedStep(
                    action="extract",
                    target="search results",
                    checkpoint=True,
                    description="Extract results",
                ),
            ],
        )
