"""
Unified Planner — Single-call plan-then-execute planner
=========================================================
Replaces the 3-call pipeline (intent_parser → task_decomposer → per-step
action_selector) with ONE LLM call that produces a structured action plan.

Output: A list of concrete browser actions with checkpoints, ready for
deterministic batch execution — no LLM needed between actions.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Optional

from ..config import AgentConfig, default_config
from ..llm_client import LLMClient
from ..model_router import ModelTier, route_for_planning
from ..models import ActionObject

logger = logging.getLogger(__name__)


class PlannedStep:
    """A single step in the execution plan."""
    __slots__ = ("action", "target", "value", "checkpoint", "description")

    def __init__(
        self, action: str, target: str = "", value: str = "",
        checkpoint: bool = False, description: str = "",
    ):
        self.action = action
        self.target = target
        self.value = value
        self.checkpoint = checkpoint
        self.description = description

    def to_action_object(self) -> ActionObject:
        """Convert to ActionObject for the browser executor."""
        selector = self.target if self.target else None
        val = self.value if self.value else None
        return ActionObject(
            action=self.action,
            selector=selector,
            value=val,
            timeout_ms=15000,
        )

    def to_dict(self) -> dict:
        return {
            "action": self.action,
            "target": self.target,
            "value": self.value,
            "checkpoint": self.checkpoint,
            "description": self.description,
        }


class ExecutionPlan:
    """Complete execution plan generated by one LLM call."""

    def __init__(
        self,
        task_type: str,
        steps: list[PlannedStep],
        success_criteria: str = "",
        domain: str = "",
    ):
        self.task_type = task_type
        self.steps = steps
        self.success_criteria = success_criteria
        self.domain = domain

    @property
    def checkpoint_indices(self) -> list[int]:
        """Return indices of steps that are checkpoints."""
        return [i for i, s in enumerate(self.steps) if s.checkpoint]


# ── PA-mode planning prompt with smart URL routing ───────────────────────────

_PLAN_PROMPT = """You are an autonomous Personal Assistant (PA) browser agent planner.
Given a user task, output a JSON action plan to accomplish it FULLY — including interactive actions like adding to cart, booking, filling forms, etc.

ACTION TYPES:
- navigate: go to a URL (value = URL)
- fill: type text into an input (target = element description, value = text to type)
- click: click a button/link (target = element description)
- scroll: scroll down the page
- extract: extract structured data from the page (target = what to extract, value = filter e.g. "cheapest")
- wait: pause for page to load (value = seconds, max 5)
- select: choose from a dropdown (target = select element, value = option text)
- press: press a keyboard key (value = key name e.g. "Enter", "Escape", "Tab")
- dismiss_popup: close popups/overlays/cookie banners before interacting

SMART WEBSITE ROUTING — pick the correct URL based on the task:
- Shopping/products/buy/price → https://www.amazon.in/ or https://www.flipkart.com/
- Flights/air travel → https://www.makemytrip.com/flights/ or https://www.google.com/travel/flights
- Train tickets/railway → https://www.irctc.co.in/ or https://www.confirmtkt.com/
- Hotels/rooms/stay → https://www.booking.com/ or https://www.oyorooms.com/
- Food delivery/restaurant → https://www.swiggy.com/ or https://www.zomato.com/
- Movies/shows → https://www.bookmyshow.com/
- Jobs/careers → https://www.linkedin.com/jobs/ or https://www.naukri.com/
- News → https://news.google.com/
- General search → https://www.google.com/
- Any specific URL mentioned by user → use that exact URL

TARGET KEYWORDS the browser understands:
- Search: "search_input", "search_button"
- Products: "cheapest_product", "first_product", "product_link"
- Cart/Buy: "add_to_cart", "buy_now", "cart_button"
- Booking: "book_now", "book_button", "reserve_button"
- Forms: "date_input", "quantity_input", "passenger_input"
- Navigation: "proceed_button", "continue_button", "next_button"
- Auth: "login_button", "sign_in"
- Popups: "close_popup", "dismiss"

RULES:
- Output ONLY valid JSON, no explanation
- Plans should be 4-10 steps for interactive tasks (booking, cart, forms)
- Plans should be 3-6 steps for search/extract tasks
- After navigate, add a dismiss_popup step to clear overlays
- After clicking a product, add a wait step for the page to load
- For add-to-cart: navigate → search → wait → click product → wait → click add_to_cart
- For booking: navigate → fill dates → fill details → click search/book → extract confirmation
- Mark the final action step as checkpoint: true
- The last step MUST be a checkpoint

USER TASK: {task}

Output JSON:
{{
  "task_type": "<product_search|purchase|booking|form_fill|price_comparison|navigation|data_extraction|account_action|other>",
  "domain": "<topic>",
  "success_criteria": "<what success looks like>",
  "steps": [
    {{"action": "navigate", "target": "", "value": "<url>", "checkpoint": false, "description": "Go to website"}},
    {{"action": "dismiss_popup", "target": "close_popup", "value": "", "checkpoint": false, "description": "Close any popups or overlays"}},
    {{"action": "fill", "target": "search_input", "value": "<search text>", "checkpoint": false, "description": "Search for query"}},
    {{"action": "wait", "target": "", "value": "3", "checkpoint": false, "description": "Wait for results to load"}},
    {{"action": "click", "target": "cheapest_product", "value": "", "checkpoint": false, "description": "Click on the product"}},
    {{"action": "wait", "target": "", "value": "3", "checkpoint": false, "description": "Wait for product page"}},
    {{"action": "click", "target": "add_to_cart", "value": "", "checkpoint": true, "description": "Add product to cart"}}
  ]
}}"""


class UnifiedPlanner:
    """
    Single-call planner that generates a complete browser action plan.

    Replaces IntentParser (M1) + TaskDecomposer (M2) for the optimized path.
    Uses model routing to pick fast vs reasoning model.
    """

    def __init__(self, config: AgentConfig = default_config):
        self.config = config
        self.llm = LLMClient(config)

    async def plan(self, task: str, retry_count: int = 0) -> tuple[ExecutionPlan, int]:
        """
        Generate a complete execution plan from a natural-language task.

        Args:
            task: User's natural-language task description.
            retry_count: Number of planning retries (triggers reasoning model).

        Returns:
            Tuple of (ExecutionPlan, tokens_used).
        """
        tier = route_for_planning(task_type="", retry_count=retry_count)
        prompt = _PLAN_PROMPT.format(task=task)

        logger.info(f"[Planner] Planning task: '{task[:80]}' (tier={tier.value})")

        if tier == ModelTier.REASONING:
            response, tokens = await self.llm.complete_reasoning(prompt)
        else:
            response, tokens = await self.llm.complete_fast(prompt)

        plan = self._parse_plan(response, task)
        logger.info(
            f"[Planner] Plan generated: {plan.task_type} | "
            f"{len(plan.steps)} steps | {len(plan.checkpoint_indices)} checkpoints | "
            f"{tokens} tokens"
        )
        return plan, tokens

    async def replan(
        self, task: str, error: str, completed_steps: list[str],
        current_url: str = "", current_title: str = "",
    ) -> tuple[ExecutionPlan, int]:
        """
        Generate a recovery plan after execution failure.
        Always uses the reasoning model.
        """
        prompt = f"""You are a browser automation recovery planner.

The original task FAILED. Generate a NEW plan to recover.

ORIGINAL TASK: {task}
ERROR: {error}
COMPLETED STEPS: {json.dumps(completed_steps)}
CURRENT PAGE: {current_url} - "{current_title}"

Output ONLY valid JSON with the same schema as before.
Focus on alternative approaches. Do NOT repeat failed actions."""

        response, tokens = await self.llm.complete_reasoning(prompt)
        plan = self._parse_plan(response, task)
        logger.info(f"[Planner] Recovery plan: {len(plan.steps)} steps | {tokens} tokens")
        return plan, tokens

    def _parse_plan(self, response: str, fallback_task: str) -> ExecutionPlan:
        """Parse LLM response into an ExecutionPlan."""
        json_match = re.search(r"\{[\s\S]*\}", response)
        if not json_match:
            logger.warning("[Planner] No JSON found, using fallback plan.")
            return self._fallback_plan(fallback_task)

        try:
            data = json.loads(json_match.group())
            steps = []
            for s in data.get("steps", []):
                steps.append(PlannedStep(
                    action=s.get("action", "wait"),
                    target=s.get("target", ""),
                    value=s.get("value", ""),
                    checkpoint=s.get("checkpoint", False),
                    description=s.get("description", ""),
                ))

            if not steps:
                return self._fallback_plan(fallback_task)

            # Ensure last step is a checkpoint
            steps[-1].checkpoint = True

            return ExecutionPlan(
                task_type=data.get("task_type", "other"),
                steps=steps,
                success_criteria=data.get("success_criteria", ""),
                domain=data.get("domain", ""),
            )
        except (json.JSONDecodeError, TypeError, ValueError, KeyError) as e:
            logger.warning(f"[Planner] Parse error: {e}. Using fallback.")
            return self._fallback_plan(fallback_task)

    @staticmethod
    def _fallback_plan(task: str) -> ExecutionPlan:
        """Minimal fallback plan when parsing fails."""
        return ExecutionPlan(
            task_type="other",
            domain="general",
            success_criteria="Complete the user's task",
            steps=[
                PlannedStep(
                    action="navigate",
                    value="https://www.google.com",
                    description="Go to Google",
                ),
                PlannedStep(
                    action="fill",
                    target="search input",
                    value=task[:100],
                    description="Search for the task",
                ),
                PlannedStep(
                    action="click",
                    target="search button",
                    checkpoint=True,
                    description="Submit search",
                ),
                PlannedStep(
                    action="extract",
                    target="search results",
                    checkpoint=True,
                    description="Extract results",
                ),
            ],
        )
